{% set version = "0.3" %}

package:
  name: setuptools_markdown
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/setuptools-markdown/setuptools-markdown-{{ version }}.tar.gz
  sha256: 89612f5cd790b7fcb25c15df25d6487c3cb2ff169a7b322012e747bb3de30d84

build:
  noarch: python
  number: 0
  preserve_egg_dir: True
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - long_description_markdown_filename = setuptools_markdown:long_description_markdown_filename

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools
    - pypandoc

test:
  imports:
    - setuptools_markdown

about:
  home: https://github.com/msabramo/setuptools-markdown
  license: MIT
  # license_file: LICENSE-MIT
  summary: 'Use Markdown for your project description'

extra:
  recipe-maintainers:
    - ocefpaf
