{% set version = "0.2" %}

package:
  name: setuptools_markdown
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/setuptools-markdown/setuptools-markdown-{{ version }}.tar.gz
  sha256: 065a6374e343b7dbb66d9d26992bbed4bdc0669f7dd744129fe109dbf214fd77

build:
  noarch: python
  number: 1
  preserve_egg_dir: True
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - long_description_markdown_filename = setuptools_markdown:long_description_markdown_filename

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools
    - pypandoc

test:
  imports:
    - setuptools_markdown

about:
  home: https://github.com/msabramo/setuptools-markdown
  license: MIT
  # license_file: LICENSE-MIT
  summary: 'Use Markdown for your project description'

extra:
  recipe-maintainers:
    - ocefpaf
