travis:
  secure:
    BINSTAR_TOKEN: uoaygBbhdARyU9XrcOn64Z/pdJggevQ30usO4lA3JD+hD+hpVAGGpltLdFjB3c6x/YoC8hD2g+KNvFtphaVOADGlwATwnSqMsnf6zCPTv3jj4zI7+PJmVpCMUW0n6qna7Cyo5DZMKThk3m7CafvI+pZbhBa7q/gtoyiLDshUSXR3gnbhMPhJHr52NCPjloCCWngHRucgOfDxGzegOwKCgNOaqDWLh+HYsJ7aQ4YdsmDOc83xEJdSG06IdQVBU0Z+4XLQfPlTi3XXAqBPv2I+ydXWtzn3kQc3dbV6DrZ4sMpBcOcRB6iT6URU8EInkcBrCe4pI3AvjS4nWZh3IERW6bYK5mezivlfvIMTa9Oxq3ApQtqEX5EJLS8XA8/0XMbKz8cQyAKDrPj1TA4tBWVMqu9UH8xDbeSVLKD2utWo5NJAkBpaxthyq6S2nLHhY6SLlPuxxv1O/U9wZrp8QGEHcSUV4xr803QstAluZ/8Xk7P0532uhZH1iEihKmJhrsolg61IWL5So8uVOhctutOPcxsWL8hruRLLKEonS+XbHm9BCwxOBteaPxOu0mCrf0D/y9T71py+o/CveYeMOBaUIPGMTK1U1YmpS5hJfcNYb65sodRhn8nrdtQIUOa1D5actKDVw083KmPQnqh6KXGm79pJo/rzRpgQS0oHmVBuEJE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
