travis:
  secure:
    BINSTAR_TOKEN: XgdKsZQk3WTZAJIdEWFUrrxR5UmkI1zAKY1LhTwXvD5PUl10nwmBtD9dTMh3LnZ2Y6haxoDyccHeE3eMNHrzULJumIh1W/HS4/RkgzFBJsPlJufHOtAPsArCoc7gwPvMufOotgDby+/PCZ0wZ2dJNwpZRhMWx/X3C8Uv8za1k4yin2NPTHx0H9y3u1LajPQ8V48Z2Z2RfUBANs1hicVefQgZQh8EWURlzQ6ia72snES1F8yIrZShw+8d0HfllGHUusVFHdyWYPiDFzrbPDjQilBAtEcsI3cdC5j/g3pnnN+NU8B2i+JJFVqIT+WV45DhF5v5o1EkXTUW0jsuRHKPhWnqB9OMzWUNCTcqwRYI/D9I5JahvIz27Cp85qFEdPmCvi85Qdcp/K8LqNBE6LDmMFHXUT+ZnP7R5+PtFIFlj0+JDbtXb4AjYZtFu2eaZukYvwn/7goLjELqvCBTu4JvyUkKwgJmP/RxA9DtwrWAMKa3EaMYSN8MJE0a+OqGLHyPOHcfYfDDYm05JCF8ndOw2F116Fs+oGqBpy2ZF8M6zHuXQbfjYeu+7iOITyXF0AFu1y5PGblTYaexutcoJhTciIKcgCjm0HeLU9Nn4Y073hSLtyle5iP0mcXJC21wS5vcZU74e7QopCd/KhUrEPre+4NntHTxKaS8w3jtgpCF6Qk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
